# Use this in your UnturnedImages/config.yaml file
- Id: "18556-18557;18582-18583" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2810935656/vehicles/{ItemId}.png" # The repository of the override.