# Use this in your UnturnedImages/config.yaml file
- Id: "13600-13601" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2802239233/items/{ItemId}.png" # The repository of the override.